"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {products} from "../../lib/catalog";
import {money,shipping,orderMessage} from "../../lib/commerce.mjs";
import {tenant,storeKey} from "../../lib/tenant";
const CART=storeKey("cart");
import localities from "../../config/localities.json";
export default function Checkout(){
const [lines,setLines]=useState(null),[draft,setDraft]=useState({mode:"pickup",fullName:"",phone:"",municipality:"",locality:"",address:"",referenceAddress:"",location:""}),[order,setOrder]=useState(null),[wa,setWa]=useState(null),[error,setError]=useState(""),[locating,setLocating]=useState(false),[confirmClear,setConfirmClear]=useState(false);
useEffect(()=>{try{const cart=JSON.parse(localStorage.getItem(CART)||"{}");setLines(products.filter(p=>Number.isInteger(cart[p.id])&&cart[p.id]>0).map(p=>({...p,quantity:Math.min(cart[p.id],99)})))}catch{setLines([])}fetch("/api/commerce/config").then(r=>r.json()).then(c=>setWa(c.whatsapp)).catch(()=>{});},[]);
const set=(key,value)=>setDraft(d=>({...d,[key]:value}));
function clearCart(){try{localStorage.removeItem(CART)}catch{}setLines([]);setOrder(null);setConfirmClear(false);setError("")}
const subtotal=(lines||[]).reduce((sum,p)=>sum+p.quantity*p.p,0),fee=shipping(draft.mode,draft.municipality,draft.locality,tenant.shippingRates);
function review(e){e.preventDefault();setError("");if(!draft.fullName.trim()||!/^\+?[\d ()-]{8,20}$/.test(draft.phone.trim())){setError("Revisa tu nombre y teléfono.");return}if(draft.mode==="delivery"&&(!localities[draft.municipality]?.includes(draft.locality)||!draft.address.trim())){setError("Selecciona municipio y localidad y escribe la dirección.");return}setOrder({...draft,fullName:draft.fullName.trim(),phone:draft.phone.trim(),reference: tenant.orderPrefix+"-"+crypto.randomUUID().slice(0,8).toUpperCase(),lines:lines.map(p=>({...p})),subtotal,fee});window.scrollTo({top:0,behavior:"smooth"})}
function locate(){setError("");if(!navigator.geolocation){setError("No se puede compartir ubicación en este navegador. Puedes continuar con la dirección.");return}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{set("location",p.coords.latitude+","+p.coords.longitude);setLocating(false)},()=>{setError("No pudimos obtener tu ubicación. Puedes continuar con la dirección escrita.");setLocating(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:60000})}
const text=order?orderMessage(order,tenant):"",url=wa&&order?wa.split("?")[0]+"?text="+encodeURIComponent(text):null;
return <main className="checkoutPage"><Link href="/" className="backLink">← Volver a la tienda</Link>
{lines===null?<p role="status">Cargando carrito…</p>:!lines.length?<section><h1>Tu carrito está vacío</h1><Link href="/">Seguir comprando</Link></section>:order?<section>
<h1>¡Tu pedido está listo para confirmar!</h1><p className="orderRef">#{order.reference}</p><p>Revisa el resumen y continúa por WhatsApp para confirmar disponibilidad y coordinación.</p>
<ul className="orderLines">{order.lines.map(p=><li key={p.id}><span>{p.quantity} × {p.n}<small>{p.d}</small></span><b>{money(p.quantity*p.p)}</b></li>)}</ul>
<dl className="orderTotals"><div><dt>Subtotal</dt><dd>{money(order.subtotal)}</dd></div><div><dt>Mensajería</dt><dd>{order.fee===null?"Por confirmar":money(order.fee)}</dd></div><div><dt>Total</dt><dd>{order.fee===null?"Pendiente de mensajería":money(order.subtotal+order.fee)}</dd></div></dl>
<p>{order.mode==="pickup"?"Recogida en "+tenant.pickupPoint:"Entrega a domicilio"}</p><p>{order.fullName}<br/>{order.phone}</p>{order.mode==="delivery"&&<p>{order.address}<br/>{order.locality}, {order.municipality}<br/>{order.referenceAddress}{order.location&&<><br/><a href={"https://www.google.com/maps/search/?api=1&query="+order.location} target="_blank" rel="noreferrer">Ver ubicación</a></>}</p>}
{url?<a className="checkoutPrimary" href={url} target="_blank" rel="noopener noreferrer">Confirmar por WhatsApp</a>:<><button className="checkoutPrimary" disabled>Confirmar por WhatsApp</button><p role="status">El mercado todavía no ha habilitado su número de WhatsApp. Puedes copiar el resumen.</p></>}
<button className="checkoutSecondary" onClick={async()=>{try{await navigator.clipboard.writeText(text);setError("Resumen copiado.")}catch{setError("Selecciona y copia el resumen que aparece debajo.")}}}>Copiar resumen</button>
<details><summary>Ver mensaje completo</summary><pre className="orderText">{text}</pre></details><button className="checkoutSecondary" onClick={()=>setOrder(null)}>Editar datos</button><Link className="checkoutSecondary" href="/">Volver a la tienda</Link>{confirmClear?<p className="cancelAsk" role="group" aria-label="Confirmar vaciado">Se borrará tu carrito. El pedido que ya enviaste por WhatsApp no se cancela solo: avísale al mercado.<button className="checkoutSecondary cancelOrder" onClick={clearCart}>Sí, vaciar carrito</button><button className="checkoutSecondary" onClick={()=>setConfirmClear(false)}>No, consérvalo</button></p>:<button className="checkoutSecondary cancelOrder" onClick={()=>setConfirmClear(true)}>Ya lo envié · Vaciar carrito</button>}
</section>:<form onSubmit={review}><h1>Completa tu pedido</h1><fieldset><legend>¿Cómo quieres recibirlo?</legend><div className="deliveryModes">{[["pickup","Recoger en tienda"],["delivery","Entrega a domicilio"]].map(([v,label])=><label key={v}><input type="radio" name="mode" checked={draft.mode===v} onChange={()=>set("mode",v)}/>{label}</label>)}</div></fieldset>
<label>Nombre y apellidos<input autoComplete="name" required maxLength={100} value={draft.fullName} onChange={e=>set("fullName",e.target.value)}/></label>
<label>Teléfono<input type="tel" inputMode="tel" autoComplete="tel" required maxLength={20} value={draft.phone} onChange={e=>set("phone",e.target.value)}/></label>
{draft.mode==="pickup"?<div className="pickupNote"><b>Recogida en {tenant.pickupPoint}</b><p>Te confirmaremos por WhatsApp cuándo tu pedido esté listo.</p></div>:<>
<label>Municipio<select required value={draft.municipality} onChange={e=>setDraft(d=>({...d,municipality:e.target.value,locality:""}))}><option value="">Selecciona municipio</option>{Object.keys(localities).map(m=><option key={m}>{m}</option>)}</select></label>
<label>Reparto o localidad<select required disabled={!draft.municipality} value={draft.locality} onChange={e=>set("locality",e.target.value)}><option value="">Selecciona reparto o localidad</option>{(localities[draft.municipality]||[]).map(l=><option key={l}>{l}</option>)}</select></label>
<label>Dirección<input required autoComplete="street-address" maxLength={250} placeholder="Calle, número, entre calles…" value={draft.address} onChange={e=>set("address",e.target.value)}/></label>
<label>Referencia<input maxLength={200} placeholder="Referencia para encontrar la dirección" value={draft.referenceAddress} onChange={e=>set("referenceAddress",e.target.value)}/></label>
<button className="checkoutSecondary" type="button" disabled={locating} onClick={locate}>{locating?"Obteniendo ubicación…":draft.location?"Actualizar ubicación":"Compartir ubicación"}</button>{draft.location&&<p role="status">Ubicación añadida <button type="button" onClick={()=>set("location","")}>Quitar</button></p>}
</>}
<dl className="orderTotals" aria-live="polite"><div><dt>Subtotal</dt><dd>{money(subtotal)}</dd></div><div><dt>Mensajería</dt><dd>{fee===null?"Por confirmar":money(fee)}</dd></div><div><dt>Total</dt><dd>{fee===null?"Pendiente de mensajería":money(subtotal+fee)}</dd></div></dl>
<p>Revisa tu pedido. Al continuar, podrás confirmar disponibilidad y coordinación por WhatsApp.</p><button type="submit" className="checkoutPrimary">Revisar pedido</button>{confirmClear?<p className="cancelAsk" role="group" aria-label="Confirmar cancelación">¿Seguro que quieres cancelar el pedido? Se vaciará tu carrito.<button type="button" className="checkoutSecondary cancelOrder" onClick={clearCart}>Sí, cancelar pedido</button><button type="button" className="checkoutSecondary" onClick={()=>setConfirmClear(false)}>No, seguir comprando</button></p>:<button type="button" className="checkoutSecondary cancelOrder" onClick={()=>setConfirmClear(true)}>Cancelar pedido</button>}</form>}
{error&&<p role="status">{error}</p>}</main>}
